# Generated by Django 5.2.8 on 2025-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('pname', models.CharField(max_length=100)),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('ptype', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
                ('warranty', models.CharField(max_length=10)),
                ('return_or_replacement_policy', models.TextField()),
                ('sellercontact', models.IntegerField()),
                ('selleremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
